### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Kubinyete** [Kubinyete/phpgallery#1]
# Lista de futuras funções e implementações

### Imagem
* [x] Pré-visualização de imagens utilizando JavaScript (nas páginas **home** & **perfil**): ![image](https://cloud.githubusercontent.com/assets/23388918/24589074/c7e4b07a-17aa-11e7-9ae5-41de567e4a99.png) ![image](https://cloud.githubusercontent.com/assets/23388918/24610095/b16e1cd8-1853-11e7-8b20-e2a48741aee6.png)

* [x] Botões de **Download**, **~~Deletar~~** & **Editar** (se o usuário logado atualmente é o autor da imagem) ![image](https://cloud.githubusercontent.com/assets/23388918/24609650/ef4d0fde-1851-11e7-9b73-6e9c37a74356.png)

* [x] Implementar a função de comentar nos Controles e Modelos de uma imagem.

* [x] Adicionar estilo nos **containers de comentários**.

### Perfil
* [x] O usuário poderá selecionar uma de suas imagens enviadas *como plano de fundo* para seu *cartão*: ![image](https://cloud.githubusercontent.com/assets/23388918/24588892/6fcf63ce-17a7-11e7-8f7f-61f69f40e35b.png)![image](https://cloud.githubusercontent.com/assets/23388918/24588921/dd4f8d8e-17a7-11e7-9e53-e0d0070f4de5.png)

* [x] O usuário poderá **editar** seu perfil, enviando imagens de perfil e escolhendo sua imagem de fundo.

* [ ] Sistema de reputação por usuário **(?)**.

### Diversos

* [x] Todos os links utilizados nas templates (Ex: a href para /login, ), deverão ser especificados na config para depois passarem a ser utilizados pelas templates através de suas respectivas Views.

* [x] Ao enviar o formulário de imagem, mostre algum tipo de animação até o upload for concluído.

* [x] **BUG** - Ao selecionar uma nova imagem de fundo, nós setamos o id da nova imagem do usuário logado porém não sua extensão.

* [ ] Adicionar **administradores**, com a habilidade de **alterar** & **remover** qualquer imagem.

* [x] Armazenar a **largura** & **altura** de uma imagem no banco de dados.

* [ ] Adicionar uma página de status do banco de dados **animada**.

* [x] Estilizar o **erroDialogo**, possível adição de *animações de transição*.

* [x] Utilizar as variáveis de configuração como **MAX_TAMANHO** para serem atribuídas nas templates contendo formulários (com campos digitáveis com propriedade **maxlength**).

* [x] Retirar o processador de miniaturas, ~~transformá-lo em um objeto~~ para criar uma imagem miniatura estática juntamente com a original (Ex: imagem1.jpg -> imagem1_min.jpg).

* [ ] Passar a obter informações das imagens através do JavaScript na visualização de imagem ao invés de trazê-las juntamente com o HTML **(?)**.

* [x] Ler todas as configurações apartir de um arquivo .ini ou .json, criar uma classe do tipo Config (Leitor de configurações) para trazer informações dos arquivos de configuração, descartando todas as classes abstratas terminadas em Config.

### Tecnologias

* [x] Utilizar um banco de dados mais leve (**MySQL** ou **SQLite**).
